# Generated by Django 5.1.1 on 2024-09-22 10:10

import account.validators
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_useraddress_city'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='phone_number',
            field=models.CharField(max_length=30, validators=[django.core.validators.RegexValidator(regex='^\\+998(90|91|93|94|95|97|98|99|33|88)\\d{7}$')]),
        ),
        migrations.AlterField(
            model_name='useraddress',
            name='phone_number',
            field=models.CharField(max_length=30, validators=[django.core.validators.RegexValidator(regex='^\\+998(90|91|93|94|95|97|98|99|33|88)\\d{7}$')]),
        ),
        migrations.AlterField(
            model_name='verificationotp',
            name='code',
            field=models.IntegerField(validators=[account.validators.check_otp_code]),
        ),
    ]
