# Generated by Django 5.1.1 on 2024-09-23 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0004_alter_user_phone_number_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='verificationotp',
            name='is_confirmed',
            field=models.BooleanField(default=False),
        ),
    ]
