# Generated by Django 5.1.1 on 2024-09-25 04:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0002_remove_region_code_alter_media_file_and_more'),
        ('product', '0002_productcolor_productimage_productreview_productsize_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='thumbnail',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='common.media'),
        ),
    ]
