# Generated by Django 5.1.1 on 2024-09-22 10:10

import common.validators
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='region',
            name='code',
        ),
        migrations.AlterField(
            model_name='media',
            name='file',
            field=models.FileField(upload_to='files/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['.png', '.jpg', 'jpeg', 'gif', 'mp4', 'mp3', 'wav', 'flac', '.doc', '.pdf'])]),
        ),
        migrations.AlterField(
            model_name='ourinstagramstories',
            name='story_link',
            field=models.URLField(validators=[common.validators.UrlCheckValidator]),
        ),
    ]
